// Generated by gencpp from file rm_msgs/ChangeTool_Name.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CHANGETOOL_NAME_H
#define RM_MSGS_MESSAGE_CHANGETOOL_NAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct ChangeTool_Name_
{
  typedef ChangeTool_Name_<ContainerAllocator> Type;

  ChangeTool_Name_()
    : toolname()  {
    }
  ChangeTool_Name_(const ContainerAllocator& _alloc)
    : toolname(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _toolname_type;
  _toolname_type toolname;





  typedef boost::shared_ptr< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeTool_Name_

typedef ::rm_msgs::ChangeTool_Name_<std::allocator<void> > ChangeTool_Name;

typedef boost::shared_ptr< ::rm_msgs::ChangeTool_Name > ChangeTool_NamePtr;
typedef boost::shared_ptr< ::rm_msgs::ChangeTool_Name const> ChangeTool_NameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ChangeTool_Name_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ChangeTool_Name_<ContainerAllocator1> & lhs, const ::rm_msgs::ChangeTool_Name_<ContainerAllocator2> & rhs)
{
  return lhs.toolname == rhs.toolname;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ChangeTool_Name_<ContainerAllocator1> & lhs, const ::rm_msgs::ChangeTool_Name_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2709e8bad159c90e287065a72644b48d";
  }

  static const char* value(const ::rm_msgs::ChangeTool_Name_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2709e8bad159c90eULL;
  static const uint64_t static_value2 = 0x287065a72644b48dULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ChangeTool_Name";
  }

  static const char* value(const ::rm_msgs::ChangeTool_Name_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string toolname\n"
;
  }

  static const char* value(const ::rm_msgs::ChangeTool_Name_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toolname);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeTool_Name_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ChangeTool_Name_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ChangeTool_Name_<ContainerAllocator>& v)
  {
    s << indent << "toolname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.toolname);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CHANGETOOL_NAME_H
