// Generated by gencpp from file rm_msgs/GetArmState_Command.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_GETARMSTATE_COMMAND_H
#define RM_MSGS_MESSAGE_GETARMSTATE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct GetArmState_Command_
{
  typedef GetArmState_Command_<ContainerAllocator> Type;

  GetArmState_Command_()
    : command()  {
    }
  GetArmState_Command_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::rm_msgs::GetArmState_Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::GetArmState_Command_<ContainerAllocator> const> ConstPtr;

}; // struct GetArmState_Command_

typedef ::rm_msgs::GetArmState_Command_<std::allocator<void> > GetArmState_Command;

typedef boost::shared_ptr< ::rm_msgs::GetArmState_Command > GetArmState_CommandPtr;
typedef boost::shared_ptr< ::rm_msgs::GetArmState_Command const> GetArmState_CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::GetArmState_Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::GetArmState_Command_<ContainerAllocator1> & lhs, const ::rm_msgs::GetArmState_Command_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::GetArmState_Command_<ContainerAllocator1> & lhs, const ::rm_msgs::GetArmState_Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::GetArmState_Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::GetArmState_Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::GetArmState_Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::rm_msgs::GetArmState_Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/GetArmState_Command";
  }

  static const char* value(const ::rm_msgs::GetArmState_Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::rm_msgs::GetArmState_Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetArmState_Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::GetArmState_Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::GetArmState_Command_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_GETARMSTATE_COMMAND_H
