// Generated by gencpp from file rm_msgs/Gripper_Pick.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_GRIPPER_PICK_H
#define RM_MSGS_MESSAGE_GRIPPER_PICK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Gripper_Pick_
{
  typedef Gripper_Pick_<ContainerAllocator> Type;

  Gripper_Pick_()
    : speed(0)
    , force(0)  {
    }
  Gripper_Pick_(const ContainerAllocator& _alloc)
    : speed(0)
    , force(0)  {
  (void)_alloc;
    }



   typedef uint16_t _speed_type;
  _speed_type speed;

   typedef uint16_t _force_type;
  _force_type force;





  typedef boost::shared_ptr< ::rm_msgs::Gripper_Pick_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Gripper_Pick_<ContainerAllocator> const> ConstPtr;

}; // struct Gripper_Pick_

typedef ::rm_msgs::Gripper_Pick_<std::allocator<void> > Gripper_Pick;

typedef boost::shared_ptr< ::rm_msgs::Gripper_Pick > Gripper_PickPtr;
typedef boost::shared_ptr< ::rm_msgs::Gripper_Pick const> Gripper_PickConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Gripper_Pick_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Gripper_Pick_<ContainerAllocator1> & lhs, const ::rm_msgs::Gripper_Pick_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.force == rhs.force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Gripper_Pick_<ContainerAllocator1> & lhs, const ::rm_msgs::Gripper_Pick_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Gripper_Pick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Gripper_Pick_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Gripper_Pick_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bccee2d260af47427a90b0534ed4c5ac";
  }

  static const char* value(const ::rm_msgs::Gripper_Pick_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbccee2d260af4742ULL;
  static const uint64_t static_value2 = 0x7a90b0534ed4c5acULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Gripper_Pick";
  }

  static const char* value(const ::rm_msgs::Gripper_Pick_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#手爪以设定的速度力控夹取，当受力超过设定力后，停止运动\n"
"uint16 speed         #1~1000,代表手爪开合速度，无量纲\n"
"uint16 force         #1～1000,代表手爪夹持力，最大1.5kg\n"
;
  }

  static const char* value(const ::rm_msgs::Gripper_Pick_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gripper_Pick_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Gripper_Pick_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Gripper_Pick_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.speed);
    s << indent << "force: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_GRIPPER_PICK_H
