// Generated by gencpp from file rm_msgs/Hand_Force.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_HAND_FORCE_H
#define RM_MSGS_MESSAGE_HAND_FORCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Hand_Force_
{
  typedef Hand_Force_<ContainerAllocator> Type;

  Hand_Force_()
    : hand_force(0)  {
    }
  Hand_Force_(const ContainerAllocator& _alloc)
    : hand_force(0)  {
  (void)_alloc;
    }



   typedef uint16_t _hand_force_type;
  _hand_force_type hand_force;





  typedef boost::shared_ptr< ::rm_msgs::Hand_Force_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Hand_Force_<ContainerAllocator> const> ConstPtr;

}; // struct Hand_Force_

typedef ::rm_msgs::Hand_Force_<std::allocator<void> > Hand_Force;

typedef boost::shared_ptr< ::rm_msgs::Hand_Force > Hand_ForcePtr;
typedef boost::shared_ptr< ::rm_msgs::Hand_Force const> Hand_ForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Hand_Force_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Hand_Force_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Hand_Force_<ContainerAllocator1> & lhs, const ::rm_msgs::Hand_Force_<ContainerAllocator2> & rhs)
{
  return lhs.hand_force == rhs.hand_force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Hand_Force_<ContainerAllocator1> & lhs, const ::rm_msgs::Hand_Force_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Hand_Force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Hand_Force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Hand_Force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Hand_Force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Hand_Force_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Hand_Force_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Hand_Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b910d20d2c9bd5f156199fd98e2fdc4";
  }

  static const char* value(const ::rm_msgs::Hand_Force_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b910d20d2c9bd5fULL;
  static const uint64_t static_value2 = 0x156199fd98e2fdc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Hand_Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Hand_Force";
  }

  static const char* value(const ::rm_msgs::Hand_Force_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Hand_Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#设置灵巧手关节力阈值\n"
"uint16 hand_force         #手指力，范围：1~1000\n"
;
  }

  static const char* value(const ::rm_msgs::Hand_Force_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Hand_Force_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hand_force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hand_Force_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Hand_Force_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Hand_Force_<ContainerAllocator>& v)
  {
    s << indent << "hand_force: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.hand_force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_HAND_FORCE_H
