// Generated by gencpp from file rm_msgs/Start_Multi_Drag_Teach.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_START_MULTI_DRAG_TEACH_H
#define RM_MSGS_MESSAGE_START_MULTI_DRAG_TEACH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Start_Multi_Drag_Teach_
{
  typedef Start_Multi_Drag_Teach_<ContainerAllocator> Type;

  Start_Multi_Drag_Teach_()
    : mode(0)  {
    }
  Start_Multi_Drag_Teach_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const> ConstPtr;

}; // struct Start_Multi_Drag_Teach_

typedef ::rm_msgs::Start_Multi_Drag_Teach_<std::allocator<void> > Start_Multi_Drag_Teach;

typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach > Start_Multi_Drag_TeachPtr;
typedef boost::shared_ptr< ::rm_msgs::Start_Multi_Drag_Teach const> Start_Multi_Drag_TeachConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator1> & lhs, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator1> & lhs, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b81386720be1cd0ce7a3953fcd1b19";
  }

  static const char* value(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b81386720be1cdULL;
  static const uint64_t static_value2 = 0x0ce7a3953fcd1b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Start_Multi_Drag_Teach";
  }

  static const char* value(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
;
  }

  static const char* value(const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Start_Multi_Drag_Teach_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Start_Multi_Drag_Teach_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_START_MULTI_DRAG_TEACH_H
