// Generated by gencpp from file rm_msgs/Tool_Analog_Output.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_TOOL_ANALOG_OUTPUT_H
#define RM_MSGS_MESSAGE_TOOL_ANALOG_OUTPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Tool_Analog_Output_
{
  typedef Tool_Analog_Output_<ContainerAllocator> Type;

  Tool_Analog_Output_()
    : voltage(0.0)  {
    }
  Tool_Analog_Output_(const ContainerAllocator& _alloc)
    : voltage(0.0)  {
  (void)_alloc;
    }



   typedef float _voltage_type;
  _voltage_type voltage;





  typedef boost::shared_ptr< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> const> ConstPtr;

}; // struct Tool_Analog_Output_

typedef ::rm_msgs::Tool_Analog_Output_<std::allocator<void> > Tool_Analog_Output;

typedef boost::shared_ptr< ::rm_msgs::Tool_Analog_Output > Tool_Analog_OutputPtr;
typedef boost::shared_ptr< ::rm_msgs::Tool_Analog_Output const> Tool_Analog_OutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator1> & lhs, const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator2> & rhs)
{
  return lhs.voltage == rhs.voltage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator1> & lhs, const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "403c816563820ece8af98cc50c8ea1ff";
  }

  static const char* value(const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x403c816563820eceULL;
  static const uint64_t static_value2 = 0x8af98cc50c8ea1ffULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Tool_Analog_Output";
  }

  static const char* value(const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32 voltage\n"
;
  }

  static const char* value(const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tool_Analog_Output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Tool_Analog_Output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Tool_Analog_Output_<ContainerAllocator>& v)
  {
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_TOOL_ANALOG_OUTPUT_H
