# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Arm_IO_State.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Arm_IO_State(genpy.Message):
  _md5sum = "dba6b2c7dc8fed61c5893347742c9c44"
  _type = "rm_msgs/Arm_IO_State"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool[3] Arm_Digital_Input
float32[4] Arm_Analog_Input
"""
  __slots__ = ['Arm_Digital_Input','Arm_Analog_Input']
  _slot_types = ['bool[3]','float32[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Arm_Digital_Input,Arm_Analog_Input

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Arm_IO_State, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Arm_Digital_Input is None:
        self.Arm_Digital_Input = [False] * 3
      if self.Arm_Analog_Input is None:
        self.Arm_Analog_Input = [0.] * 4
    else:
      self.Arm_Digital_Input = [False] * 3
      self.Arm_Analog_Input = [0.] * 4

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_3B().pack(*self.Arm_Digital_Input))
      buff.write(_get_struct_4f().pack(*self.Arm_Analog_Input))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 3
      self.Arm_Digital_Input = _get_struct_3B().unpack(str[start:end])
      self.Arm_Digital_Input = list(map(bool, self.Arm_Digital_Input))
      start = end
      end += 16
      self.Arm_Analog_Input = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.Arm_Digital_Input.tostring())
      buff.write(self.Arm_Analog_Input.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 3
      self.Arm_Digital_Input = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=3)
      self.Arm_Digital_Input = list(map(bool, self.Arm_Digital_Input))
      start = end
      end += 16
      self.Arm_Analog_Input = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
