# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Force_Position_Move_Pose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Force_Position_Move_Pose(genpy.Message):
  _md5sum = "d767ae12238c9954eb73a3ce727611a5"
  _type = "rm_msgs/Force_Position_Move_Pose"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose Pose
uint8 sensor
uint8 mode
uint8 dir
int16 force

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['Pose','sensor','mode','dir','force']
  _slot_types = ['geometry_msgs/Pose','uint8','uint8','uint8','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Pose,sensor,mode,dir,force

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Force_Position_Move_Pose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Pose is None:
        self.Pose = geometry_msgs.msg.Pose()
      if self.sensor is None:
        self.sensor = 0
      if self.mode is None:
        self.mode = 0
      if self.dir is None:
        self.dir = 0
      if self.force is None:
        self.force = 0
    else:
      self.Pose = geometry_msgs.msg.Pose()
      self.sensor = 0
      self.mode = 0
      self.dir = 0
      self.force = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d3Bh().pack(_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.sensor, _x.mode, _x.dir, _x.force))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Pose is None:
        self.Pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.sensor, _x.mode, _x.dir, _x.force,) = _get_struct_7d3Bh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d3Bh().pack(_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.sensor, _x.mode, _x.dir, _x.force))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Pose is None:
        self.Pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.Pose.position.x, _x.Pose.position.y, _x.Pose.position.z, _x.Pose.orientation.x, _x.Pose.orientation.y, _x.Pose.orientation.z, _x.Pose.orientation.w, _x.sensor, _x.mode, _x.dir, _x.force,) = _get_struct_7d3Bh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d3Bh = None
def _get_struct_7d3Bh():
    global _struct_7d3Bh
    if _struct_7d3Bh is None:
        _struct_7d3Bh = struct.Struct("<7d3Bh")
    return _struct_7d3Bh
