# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/Tool_IO_State.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Tool_IO_State(genpy.Message):
  _md5sum = "d7adff68dc996b192b01391906704f92"
  _type = "rm_msgs/Tool_IO_State"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool[2] Tool_Digital_Input
float32 Tool_Analog_Input
"""
  __slots__ = ['Tool_Digital_Input','Tool_Analog_Input']
  _slot_types = ['bool[2]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Tool_Digital_Input,Tool_Analog_Input

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Tool_IO_State, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Tool_Digital_Input is None:
        self.Tool_Digital_Input = [False] * 2
      if self.Tool_Analog_Input is None:
        self.Tool_Analog_Input = 0.
    else:
      self.Tool_Digital_Input = [False] * 2
      self.Tool_Analog_Input = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_2B().pack(*self.Tool_Digital_Input))
      _x = self.Tool_Analog_Input
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 2
      self.Tool_Digital_Input = _get_struct_2B().unpack(str[start:end])
      self.Tool_Digital_Input = list(map(bool, self.Tool_Digital_Input))
      start = end
      end += 4
      (self.Tool_Analog_Input,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.Tool_Digital_Input.tostring())
      _x = self.Tool_Analog_Input
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 2
      self.Tool_Digital_Input = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=2)
      self.Tool_Digital_Input = list(map(bool, self.Tool_Digital_Input))
      start = end
      end += 4
      (self.Tool_Analog_Input,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
